USE [IAMDB]
GO
ALTER TABLE SECU.TBL_CODIGO_VERIFICACION
ADD CONSTRAINT FK_ID_Usuario_TBL_CODIGO_VERIFICACION FOREIGN KEY(ID_Usuario) REFERENCES SECU.TBL_USUARIOS (ID_Usuario);
ALTER TABLE SECU.TBL_CODIGO_VERIFICACION
ADD CONSTRAINT FK_TBL_CODIGO_VERIFICACION_ESTADO FOREIGN KEY (ID_Estado) REFERENCES UTIL.TBL_ESTADOS (ID_Estado);