use [IAMDB]
GO

INSERT INTO UTIL.TBL_ESTADOS (ID_Estado, Nombre, Tabla) VALUES (32, 'Activo', 'TBL_CODIGO_VERIFICACION');
INSERT INTO UTIL.TBL_ESTADOS (ID_Estado, Nombre, Tabla) VALUES (33, 'Inactivo', 'TBL_CODIGO_VERIFICACION');
INSERT INTO UTIL.TBL_ESTADOS (ID_Estado, Nombre, Tabla) VALUES (34, 'Verificado', 'TBL_CODIGO_VERIFICACION');
INSERT INTO UTIL.TBL_ESTADOS (ID_Estado, Nombre, Tabla) VALUES (35, 'Por Validar', 'TBL_USUARIOS');