USE [IAMDB]
GO
-- Alter Primary Key--
ALTER TABLE SECU.TBL_USUARIOS ADD CONSTRAINT PK_TBL_USUARIOS PRIMARY KEY (ID_Usuario)
ALTER TABLE UTIL.TBL_ESTADOS ADD CONSTRAINT PK_TBL_ESTADOS PRIMARY KEY (ID_Estado)
ALTER TABLE CORE.TBL_NEGOCIOS ADD CONSTRAINT PK_TBL_NEGOCIOS PRIMARY KEY (ID_Negocio)
ALTER TABLE CORE.TBL_CLIENTES ADD CONSTRAINT PK_TBL_CLIENTES PRIMARY KEY (ID_Cliente)
ALTER TABLE CORE.TBL_ORDENES_SERVICIO ADD CONSTRAINT PK_TBL_ORDENES_SERVICIO PRIMARY KEY (ID_OrdenServicio)
ALTER TABLE CORE.TBL_TRANSACCIONES ADD CONSTRAINT PK_TBL_TRANSACCIONES PRIMARY KEY (ID_Transaccion)
ALTER TABLE CORE.TBL_ITEMS_ORDEN_SERVICIO ADD CONSTRAINT PK_TBL_ITEMS_ORDEN_SERVICIO PRIMARY KEY (ID_ItemOrdenServicio)
ALTER TABLE CORE.TBL_CUENTAS_POR_PAGAR ADD CONSTRAINT PK_TBL_CUENTAS_POR_PAGAR PRIMARY KEY (ID_CuentasPorPagar)
ALTER TABLE CORE.TBL_CHAT_IA ADD CONSTRAINT PK_TBL_CHAT_IA PRIMARY KEY (ID_ChatIA)
ALTER TABLE CORE.TBL_MENSAJES_CHAT ADD CONSTRAINT PK_TBL_MENSAJES_CHAT PRIMARY KEY (ID_Mensaje)
ALTER TABLE CORE.TBL_INTENCIONES_DETECTADAS ADD CONSTRAINT PK_TBL_INTENCIONES_DETECTADAS PRIMARY KEY (ID_Intencion)
ALTER TABLE CORE.TBL_PARAMETROS_POR_INTENCION ADD CONSTRAINT PK_TBL_PARAMETROS_POR_INTENCION PRIMARY KEY (ID_Parametro)
ALTER TABLE UTIL.TBL_LOG_ERRORES ADD CONSTRAINT PK_TBL_LOG_ERRORES PRIMARY KEY (ID_LOG)
ALTER TABLE SECU.TBL_SESIONES ADD CONSTRAINT PK_TBL_SESIONES PRIMARY KEY (ID_SESION)
ALTER TABLE SECU.TBL_Roles ADD CONSTRAINT PK_TBL_Roles PRIMARY KEY (ID_Rol)
ALTER TABLE UTIL.TBL_ALERTAS ADD CONSTRAINT PK_TBL_ALERTAS PRIMARY KEY (COD_Alerta)