USE [IAMDB]
GO

-- Alters Foreing Key
--Nomenclatura FK_<nombre del campo de la tabla que se altera>_<nombre la tabla que se altera>
ALTER TABLE SECU.TBL_USUARIOS ADD CONSTRAINT FK_ID_Estado_TBL_USUARIOS FOREIGN KEY(ID_Estado) REFERENCES UTIL.TBL_ESTADOS(ID_Estado)
ALTER TABLE CORE.TBL_NEGOCIOS ADD CONSTRAINT FK_ID_Usuario_TBL_NEGOCIOS FOREIGN KEY(ID_Usuario) REFERENCES SECU.TBL_USUARIOS (ID_Usuario)
ALTER TABLE CORE.TBL_NEGOCIOS ADD CONSTRAINT FK_ID_Estado_TBL_NEGOCIOS FOREIGN KEY(ID_Estado) REFERENCES UTIL.TBL_ESTADOS (ID_Estado)
ALTER TABLE CORE.TBL_CLIENTES ADD CONSTRAINT FK_ID_Usuario_TBL_CLIENTES FOREIGN KEY(ID_Usuario) REFERENCES SECU.TBL_USUARIOS (ID_Usuario)
ALTER TABLE CORE.TBL_CLIENTES ADD CONSTRAINT FK_ID_Estado_TBL_CLIENTES FOREIGN KEY(ID_Estado) REFERENCES UTIL.TBL_ESTADOS (ID_Estado)
ALTER TABLE CORE.TBL_ORDENES_SERVICIO ADD CONSTRAINT FK_ID_Cliente_TBL_ORDENES_SERVICIO FOREIGN KEY(ID_Cliente) REFERENCES CORE.TBL_CLIENTES (ID_Cliente)
ALTER TABLE CORE.TBL_ORDENES_SERVICIO ADD CONSTRAINT FK_ID_Cliente_TBL_ORDENES_SERVICIO FOREIGN KEY(ID_Cliente) REFERENCES CORE.TBL_CLIENTES (ID_Cliente)
ALTER TABLE CORE.TBL_ORDENES_SERVICIO ADD CONSTRAINT FK_ID_Negocio_TBL_NEGOCIOS FOREIGN KEY(ID_Negocio) REFERENCES CORE.TBL_NEGOCIOS (ID_Negocio)
ALTER TABLE CORE.TBL_ORDENES_SERVICIO ADD CONSTRAINT FK_ID_Estado_TBL_ORDENES_SERVICIO FOREIGN KEY(ID_Estado) REFERENCES UTIL.TBL_ESTADOS (ID_Estado)
ALTER TABLE CORE.TBL_TRANSACCIONES ADD CONSTRAINT FK_ID_Negocio_TBL_TRANSACCIONES FOREIGN KEY(ID_Negocio) REFERENCES CORE.TBL_NEGOCIOS (ID_Negocio)
ALTER TABLE CORE.TBL_ITEMS_ORDEN_SERVICIO ADD CONSTRAINT FK_ID_OrdenServicio_TBL_ITEMS_ORDEN_SERVICIO FOREIGN KEY(ID_OrdenServicio) REFERENCES CORE.TBL_ORDENES_SERVICIO (ID_OrdenServicio)
ALTER TABLE CORE.TBL_ITEMS_ORDEN_SERVICIO ADD CONSTRAINT FK_ID_Estado_TBL_ITEMS_ORDEN_SERVICIO FOREIGN KEY(ID_Estado) REFERENCES UTIL.TBL_ESTADOS (ID_Estado)
ALTER TABLE CORE.TBL_CUENTAS_POR_PAGAR ADD CONSTRAINT FK_ID_Negocio_TBL_CUENTAS_POR_PAGAR FOREIGN KEY(ID_Negocio) REFERENCES CORE.TBL_NEGOCIOS (ID_Negocio)
ALTER TABLE CORE.TBL_CUENTAS_POR_PAGAR ADD CONSTRAINT FK_ID_Estado_TBL_CUENTAS_POR_PAGAR FOREIGN KEY(ID_Estado) REFERENCES UTIL.TBL_ESTADOS (ID_Estado)
ALTER TABLE CORE.TBL_CHAT_IA ADD CONSTRAINT FK_ID_Negocio_TBL_CHAT_IA FOREIGN KEY(ID_Negocio) REFERENCES CORE.TBL_NEGOCIOS (ID_Negocio)
ALTER TABLE CORE.TBL_CHAT_IA ADD CONSTRAINT FK_ID_Estado_TBL_CHAT_IA FOREIGN KEY(ID_Estado) REFERENCES UTIL.TBL_ESTADOS (ID_Estado)
ALTER TABLE CORE.TBL_MENSAJES_CHAT ADD CONSTRAINT FK_ID_ChatIA_TBL_MENSAJES_CHAT FOREIGN KEY(ID_ChatIA) REFERENCES CORE.TBL_CHAT_IA (ID_ChatIA)
ALTER TABLE CORE.TBL_INTENCIONES_DETECTADAS ADD CONSTRAINT FK_ID_Estado_TBL_INTENCIONES_DETECTADAS FOREIGN KEY(ID_Estado) REFERENCES UTIL.TBL_ESTADOS (ID_Estado)
ALTER TABLE CORE.TBL_INTENCIONES_DETECTADAS ADD CONSTRAINT FK_ID_ChatIA_TBL_INTENCIONES_DETECTADAS FOREIGN KEY(ID_ChatIA) REFERENCES CORE.TBL_CHAT_IA (ID_ChatIA)
ALTER TABLE CORE.TBL_PARAMETROS_POR_INTENCION ADD CONSTRAINT FK_ID_Intencion_TBL_PARAMETROS_POR_INTENCION FOREIGN KEY(ID_Intencion) REFERENCES CORE.TBL_INTENCIONES_DETECTADAS (ID_Intencion)
ALTER TABLE CORE.TBL_PARAMETROS_POR_INTENCION ADD CONSTRAINT FK_ID_Estado_TBL_PARAMETROS_POR_INTENCION FOREIGN KEY(ID_Estado) REFERENCES UTIL.TBL_ESTADOS (ID_Estado)
ALTER TABLE SECU.TBL_SESIONES ADD CONSTRAINT FK_ID_Usuario_TBL_SESIONES FOREIGN KEY(ID_Usuario) REFERENCES SECU.TBL_USUARIOS (ID_Usuario)
ALTER TABLE SECU.TBL_USUARIOS ADD CONSTRAINT FK_ID_Rol_TBL_USUARIOS FOREIGN KEY(ID_Rol) REFERENCES SECU.TBL_Roles (ID_Rol)
ALTER TABLE CORE.TBL_TRANSACCIONES ADD CONSTRAINT FK_ID_Estado_TBL_TRANSACCIONES FOREIGN KEY(ID_Estado) REFERENCES UTIL.TBL_ESTADOS (ID_Estado)