USE [master]
GO

CREATE LOGIN [QA_User] WITH PASSWORD=N'qa123456789', DEFAULT_DATABASE=[IAMDB], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

ALTER LOGIN [QA_User] ENABLE
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [QA_User]
GO


