import { FieldConfig } from "@/components/Modals/GenericFormModal/types";
import { DTO_Cliente, DTO_Cuenta, DTO_ItemOrdenServicio, DTO_Negocio, DTO_OrdenServicio, DTO_Transacciones } from "@/models";
export declare const columnKeysCuenta: (keyof DTO_Cuenta)[];
export declare const columnKeysNegocio: (keyof DTO_Negocio)[];
export declare const columnKeysOrdenDeServicio: (keyof DTO_OrdenServicio)[];
export declare const columnKeysCliente: (keyof DTO_Cliente)[];
export declare const columnKeysItemsOrdenServicio: (keyof DTO_ItemOrdenServicio)[];
export declare const columnKeysTransacciones: (keyof DTO_Transacciones)[];
export declare const keysInfoModalOrdenDeServicio: (keyof DTO_OrdenServicio)[];
export declare const keysInfoModalNegocio: (keyof DTO_Negocio)[];
export declare const keysInfoModalCuenta: (keyof DTO_Cuenta)[];
export declare const keysInfoModalCliente: (keyof DTO_Cliente)[];
export declare const keysInfoModalItemsOrdenServicio: (keyof DTO_ItemOrdenServicio)[];
export declare const keysInfoModalTransacciones: (keyof DTO_Transacciones)[];
export declare const labelMapCuenta: Record<string, string>;
export declare const labelMapNegocio: Record<string, string>;
export declare const labelMapOrdenDeServicio: Record<string, string>;
export declare const labelMapCliente: Record<string, string>;
export declare const labelMapItemsOrdenServicio: Record<string, string>;
export declare const labelMapTransacciones: Record<string, string>;
export declare const negocioFormEditFields: Array<FieldConfig<DTO_Negocio>>;
export declare const cuentasFormEditFields: FieldConfig<DTO_Cuenta>[];
export declare const clienteFormEditFields: Array<FieldConfig<DTO_Cliente>>;
export declare const ItemsOrdenServicioFormEditFields: Array<FieldConfig<DTO_ItemOrdenServicio>>;
export declare const ordenServicioFormEditFields: Array<FieldConfig<DTO_OrdenServicio>>;
export declare const transaccionesFormEditFields: FieldConfig<DTO_Transacciones>[];
