export declare const ROUTES: {
    readonly HOME: "/home";
    readonly ABOUT: "/about";
    readonly STATISTICS: "/statistics";
    readonly CHAT_AI: "/chat";
    readonly CONTACT: "/contact";
    readonly SERVICES: "/services";
    readonly BLOG: "/blog";
    readonly LOGIN: "/login";
    readonly SIGNUP: "/sign-up";
    readonly REGISTER: "/register";
    readonly PROFILE: "/profile";
    readonly DASHBOARD: "/dashboard";
    readonly SETTINGS: "/settings";
    readonly HELP: "/help";
    readonly TERMS: "/terms";
    readonly PRIVACY: "/privacy";
    readonly NEGOCIO: "/negocio";
    readonly MONITOR: "/monitor";
    readonly CUENTAS: "/cuentas";
    readonly CLIENTES: "/clientes";
    readonly TRANSACTIONS: "/transactions";
    readonly SERVICE_ORDER: "/orden-servicio";
    readonly METRICAS: "/metricas";
    readonly NOT_FOUND: "*";
};
export type RouteKeys = keyof typeof ROUTES;
export type RouteValues = (typeof ROUTES)[RouteKeys];
